/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Fit App API
 * Documentação da API do Fit App
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type GetWorkoutPlansParams = {
  active?: string;
};

export type GetWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const GetWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: GetWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRestDay: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type GetWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: GetWorkoutPlans200ItemWorkoutDaysItem[];
};

export type GetWorkoutPlans401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  /** @nullable */
  coverImageUrl?: string | null;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRestDay?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  /** @nullable */
  coverImageUrl?: string | null;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRestDay: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById200WeekDay =
  (typeof GetWorkoutDayById200WeekDay)[keyof typeof GetWorkoutDayById200WeekDay];

export const GetWorkoutDayById200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDayById200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutDayById200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @nullable */
  startedAt?: string | null;
  /** @nullable */
  completedAt?: string | null;
};

export type GetWorkoutDayById200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRestDay: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDayById200WeekDay;
  exercises: GetWorkoutDayById200ExercisesItem[];
  sessions: GetWorkoutDayById200SessionsItem[];
};

export type GetWorkoutDayById401 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById403 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById404 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlanById200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlanById200WorkoutDaysItemWeekDay];

export const GetWorkoutPlanById200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlanById200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlanById200WorkoutDaysItemWeekDay;
  name: string;
  isRestDay: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlanById200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlanById200WorkoutDaysItem[];
};

export type GetWorkoutPlanById401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById403 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
};

export type StartWorkoutSession400 = {
  error: string;
  code: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession403 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSessionBody = {
  statusMessage?: string;
  taggedUserIds?: string[];
  imageUrl?: string;
};

export type CompleteWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
};

export type CompleteWorkoutSession400 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession401 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession403 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession404 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession409 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpsertWorkoutSetBody = {
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  reps: number;
};

/**
 * @nullable
 */
export type UpsertWorkoutSet204 =
  | (typeof UpsertWorkoutSet204)[keyof typeof UpsertWorkoutSet204]
  | null;

export const UpsertWorkoutSet204 = {} as const;

export type UpsertWorkoutSet401 = {
  error: string;
  code: string;
};

export type UpsertWorkoutSet404 = {
  error: string;
  code: string;
};

export type UpsertWorkoutSet500 = {
  error: string;
  code: string;
};

export type Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  sessionId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutExerciseId: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  setIndex: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  reps: number;
  createdAt: string;
};

/**
 * @nullable
 */
export type GetWorkoutExerciseHistory200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | 00000000-0000-0000-0000-000000000000 | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  exerciseId: string;
  lastSets: Item[];
} | null;

export type GetWorkoutExerciseHistory401 = {
  error: string;
  code: string;
};

export type GetWorkoutExerciseHistory500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | 00000000-0000-0000-0000-000000000000 | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRestDay: boolean;
  weekDay:
    | "MONDAY"
    | "TUESDAY"
    | "WEDNESDAY"
    | "THURSDAY"
    | "FRIDAY"
    | "SATURDAY"
    | "SUNDAY";
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercisesCount: number;
} | null;

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  activeWorkoutPlanId: string | null;
  /** @nullable */
  todayWorkoutDay: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  from: string;
  /**
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  completedRestDays: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
  totalVolumeInGrams: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

export type GetMe200 = {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  image: string | null;
  /** @nullable */
  friendCode: string | null;
  xp: number;
  level: number;
  isPublicProfile: boolean;
  showStats: boolean;
};

export type GetMe401 = {
  error: string;
  code: string;
};

export type GetMe404 = {
  error: string;
  code: string;
};

export type GetMe500 = {
  error: string;
  code: string;
};

export type GetFriends200Item = {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  image: string | null;
  /** @nullable */
  friendCode: string | null;
  since: string;
};

export type GetFriends401 = {
  error: string;
  code: string;
};

export type GetFriends500 = {
  error: string;
  code: string;
};

export type AddFriendBody = {
  /** @minLength 1 */
  codeOrEmail: string;
};

export type AddFriend200 = {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  image: string | null;
  /** @nullable */
  friendCode: string | null;
  xp: number;
  level: number;
  isPublicProfile: boolean;
  showStats: boolean;
};

export type AddFriend400 = {
  error: string;
  code: string;
};

export type AddFriend401 = {
  error: string;
  code: string;
};

export type AddFriend404 = {
  error: string;
  code: string;
};

export type AddFriend500 = {
  error: string;
  code: string;
};

export type GetFriendRequestsParams = {
  type?: GetFriendRequestsType;
};

export type GetFriendRequestsType =
  (typeof GetFriendRequestsType)[keyof typeof GetFriendRequestsType];

export const GetFriendRequestsType = {
  RECEIVED: "RECEIVED",
  SENT: "SENT",
} as const;

export type GetFriendRequests200ItemStatus =
  (typeof GetFriendRequests200ItemStatus)[keyof typeof GetFriendRequests200ItemStatus];

export const GetFriendRequests200ItemStatus = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
} as const;

export type GetFriendRequests200ItemUser = {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  image: string | null;
};

export type GetFriendRequests200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  status: GetFriendRequests200ItemStatus;
  createdAt: string;
  user: GetFriendRequests200ItemUser;
};

export type GetFriendRequests401 = {
  error: string;
  code: string;
};

export type GetFriendRequests500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type AcceptFriendRequest204 =
  | (typeof AcceptFriendRequest204)[keyof typeof AcceptFriendRequest204]
  | null;

export const AcceptFriendRequest204 = {} as const;

export type AcceptFriendRequest401 = {
  error: string;
  code: string;
};

export type AcceptFriendRequest404 = {
  error: string;
  code: string;
};

export type AcceptFriendRequest500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type DeclineFriendRequest204 =
  | (typeof DeclineFriendRequest204)[keyof typeof DeclineFriendRequest204]
  | null;

export const DeclineFriendRequest204 = {} as const;

export type DeclineFriendRequest401 = {
  error: string;
  code: string;
};

export type DeclineFriendRequest404 = {
  error: string;
  code: string;
};

export type DeclineFriendRequest500 = {
  error: string;
  code: string;
};

export type GetFeedParams = {
  /**
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  cursor?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetFeed200ActivitiesItemCommentsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
  userName: string;
  /** @nullable */
  userImage: string | null;
  content: string;
  createdAt: string;
};

export type GetFeed200ActivitiesItemTaggedUsersItem = {
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
};

export type GetFeed200ActivitiesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
  userName: string;
  /** @nullable */
  userImage: string | null;
  workoutDayName: string;
  workoutPlanName: string;
  /** @nullable */
  statusMessage: string | null;
  /** @nullable */
  imageUrl: string | null;
  startedAt: string;
  completedAt: string;
  powerupsCount: number;
  hasPowerupByMe: boolean;
  createdAt: string;
  comments: GetFeed200ActivitiesItemCommentsItem[];
  taggedUsers: GetFeed200ActivitiesItemTaggedUsersItem[];
};

export type GetFeed200 = {
  activities: GetFeed200ActivitiesItem[];
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  nextCursor: string | null;
};

export type GetFeed401 = {
  error: string;
  code: string;
};

export type GetFeed500 = {
  error: string;
  code: string;
};

export type GetUserFeedParams = {
  /**
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  cursor?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetUserFeed200ActivitiesItemCommentsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
  userName: string;
  /** @nullable */
  userImage: string | null;
  content: string;
  createdAt: string;
};

export type GetUserFeed200ActivitiesItemTaggedUsersItem = {
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
};

export type GetUserFeed200ActivitiesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
  userName: string;
  /** @nullable */
  userImage: string | null;
  workoutDayName: string;
  workoutPlanName: string;
  /** @nullable */
  statusMessage: string | null;
  /** @nullable */
  imageUrl: string | null;
  startedAt: string;
  completedAt: string;
  powerupsCount: number;
  hasPowerupByMe: boolean;
  createdAt: string;
  comments: GetUserFeed200ActivitiesItemCommentsItem[];
  taggedUsers: GetUserFeed200ActivitiesItemTaggedUsersItem[];
};

export type GetUserFeed200 = {
  activities: GetUserFeed200ActivitiesItem[];
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  nextCursor: string | null;
};

export type GetUserFeed401 = {
  error: string;
  code: string;
};

export type GetUserFeed403 = {
  error: string;
  code: string;
};

export type GetUserFeed500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type TogglePowerup204 =
  | (typeof TogglePowerup204)[keyof typeof TogglePowerup204]
  | null;

export const TogglePowerup204 = {} as const;

export type TogglePowerup401 = {
  error: string;
  code: string;
};

export type TogglePowerup403 = {
  error: string;
  code: string;
};

export type TogglePowerup404 = {
  error: string;
  code: string;
};

export type TogglePowerup500 = {
  error: string;
  code: string;
};

export type AddCommentBody = {
  /**
   * @minLength 1
   * @maxLength 500
   */
  content: string;
};

/**
 * @nullable
 */
export type AddComment204 =
  | (typeof AddComment204)[keyof typeof AddComment204]
  | null;

export const AddComment204 = {} as const;

export type AddComment401 = {
  error: string;
  code: string;
};

export type AddComment404 = {
  error: string;
  code: string;
};

export type AddComment500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type DeleteActivity204 =
  | (typeof DeleteActivity204)[keyof typeof DeleteActivity204]
  | null;

export const DeleteActivity204 = {} as const;

export type DeleteActivity401 = {
  error: string;
  code: string;
};

export type DeleteActivity403 = {
  error: string;
  code: string;
};

export type DeleteActivity404 = {
  error: string;
  code: string;
};

export type DeleteActivity500 = {
  error: string;
  code: string;
};

export type GetNotificationsParams = {
  /**
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  cursor?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetNotifications200NotificationsItemType =
  (typeof GetNotifications200NotificationsItemType)[keyof typeof GetNotifications200NotificationsItemType];

export const GetNotifications200NotificationsItemType = {
  FRIEND_REQUEST: "FRIEND_REQUEST",
  FRIEND_ACCEPTED: "FRIEND_ACCEPTED",
  POWERUP_RECEIVED: "POWERUP_RECEIVED",
  LEVEL_UP: "LEVEL_UP",
  ACHIEVEMENT_UNLOCKED: "ACHIEVEMENT_UNLOCKED",
  CHALLENGE_INVITE: "CHALLENGE_INVITE",
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  TAGGED_IN_ACTIVITY: "TAGGED_IN_ACTIVITY",
  PERSONAL_RECORD_BROKEN: "PERSONAL_RECORD_BROKEN",
} as const;

/**
 * @nullable
 */
export type GetNotifications200NotificationsItemSender = {
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
} | null;

/**
 * @nullable
 */
export type GetNotifications200NotificationsItemAchievement = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | 00000000-0000-0000-0000-000000000000 | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  iconUrl: string | null;
} | null;

export type GetNotifications200NotificationsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  type: GetNotifications200NotificationsItemType;
  isRead: boolean;
  createdAt: string;
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  activityId: string | null;
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  achievementId: string | null;
  /** @nullable */
  content: string | null;
  /** @nullable */
  sender: GetNotifications200NotificationsItemSender;
  /** @nullable */
  achievement: GetNotifications200NotificationsItemAchievement;
};

export type GetNotifications200 = {
  notifications: GetNotifications200NotificationsItem[];
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  nextCursor: string | null;
};

export type GetNotifications401 = {
  error: string;
  code: string;
};

export type GetNotifications500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type MarkAllNotificationsAsRead204 =
  | (typeof MarkAllNotificationsAsRead204)[keyof typeof MarkAllNotificationsAsRead204]
  | null;

export const MarkAllNotificationsAsRead204 = {} as const;

export type MarkAllNotificationsAsRead401 = {
  error: string;
  code: string;
};

export type MarkAllNotificationsAsRead500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type MarkNotificationAsRead204 =
  | (typeof MarkNotificationAsRead204)[keyof typeof MarkNotificationAsRead204]
  | null;

export const MarkNotificationAsRead204 = {} as const;

export type MarkNotificationAsRead401 = {
  error: string;
  code: string;
};

export type MarkNotificationAsRead404 = {
  error: string;
  code: string;
};

export type MarkNotificationAsRead500 = {
  error: string;
  code: string;
};

export type GetAchievements200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  description: string;
  /** @nullable */
  iconUrl: string | null;
  xpReward: number;
  /** @nullable */
  unlockedAt?: string | null;
};

export type GetAchievements401 = {
  error: string;
  code: string;
};

export type GetAchievements500 = {
  error: string;
  code: string;
};

export type GetChallenges200ItemType =
  (typeof GetChallenges200ItemType)[keyof typeof GetChallenges200ItemType];

export const GetChallenges200ItemType = {
  GLOBAL: "GLOBAL",
  FRIEND_DUEL: "FRIEND_DUEL",
} as const;

export type GetChallenges200ItemStatus =
  (typeof GetChallenges200ItemStatus)[keyof typeof GetChallenges200ItemStatus];

export const GetChallenges200ItemStatus = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
} as const;

export type GetChallenges200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  description: string;
  type: GetChallenges200ItemType;
  status: GetChallenges200ItemStatus;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  xpReward: number;
  participantsCount: number;
  isJoined: boolean;
};

export type GetChallenges401 = {
  error: string;
  code: string;
};

export type GetChallenges500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type JoinChallenge204 =
  | (typeof JoinChallenge204)[keyof typeof JoinChallenge204]
  | null;

export const JoinChallenge204 = {} as const;

export type JoinChallenge401 = {
  error: string;
  code: string;
};

export type JoinChallenge404 = {
  error: string;
  code: string;
};

export type JoinChallenge500 = {
  error: string;
  code: string;
};

export type GetXpHistory200ItemReason =
  (typeof GetXpHistory200ItemReason)[keyof typeof GetXpHistory200ItemReason];

export const GetXpHistory200ItemReason = {
  WORKOUT_COMPLETED: "WORKOUT_COMPLETED",
  PERSONAL_RECORD: "PERSONAL_RECORD",
  STREAK_7_DAYS: "STREAK_7_DAYS",
  STREAK_30_DAYS: "STREAK_30_DAYS",
  POWERUP_GIVEN: "POWERUP_GIVEN",
  POWERUP_RECEIVED: "POWERUP_RECEIVED",
  FRIEND_ACCEPTED: "FRIEND_ACCEPTED",
  CHALLENGE_COMPLETED: "CHALLENGE_COMPLETED",
  CHALLENGE_WON: "CHALLENGE_WON",
  COMMENT_GIVEN: "COMMENT_GIVEN",
} as const;

export type GetXpHistory200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  amount: number;
  reason: GetXpHistory200ItemReason;
  createdAt: string;
};

export type GetXpHistory401 = {
  error: string;
  code: string;
};

export type GetXpHistory500 = {
  error: string;
  code: string;
};

export type UpdateProfileBody = {
  /** @minLength 1 */
  name?: string;
  image?: string;
};

export type UpdateProfile200 = {
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
};

export type UpdateProfile401 = {
  error: string;
  code: string;
};

export type UpdateProfile500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  age: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  age: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

export type SearchUsersParams = {
  /**
   * @minLength 1
   */
  query: string;
};

export type SearchUsers200Item = {
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
  /** @nullable */
  friendCode: string | null;
  level: number;
  isFriend: boolean;
  isPending: boolean;
};

export type SearchUsers401 = {
  error: string;
  code: string;
};

export type SearchUsers500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserProfile200Stats = {
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetUserProfile200AchievementsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  iconUrl: string | null;
  unlockedAt: string;
};

export type GetUserProfile200 = {
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
  level: number;
  xp: number;
  streak: number;
  isFriend: boolean;
  isPending: boolean;
  /** @nullable */
  stats: GetUserProfile200Stats;
  achievements: GetUserProfile200AchievementsItem[];
};

export type GetUserProfile401 = {
  error: string;
  code: string;
};

export type GetUserProfile403 = {
  error: string;
  code: string;
};

export type GetUserProfile404 = {
  error: string;
  code: string;
};

export type GetUserProfile500 = {
  error: string;
  code: string;
};

export type UpdatePrivacySettingsBody = {
  isPublicProfile?: boolean;
  showStats?: boolean;
};

/**
 * @nullable
 */
export type UpdatePrivacySettings204 =
  | (typeof UpdatePrivacySettings204)[keyof typeof UpdatePrivacySettings204]
  | null;

export const UpdatePrivacySettings204 = {} as const;

export type UpdatePrivacySettings401 = {
  error: string;
  code: string;
};

export type UpdatePrivacySettings500 = {
  error: string;
  code: string;
};

export type GetPersonalRecords200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  exerciseName: string;
  weightInGrams: number;
  reps: number;
  achievedAt: string;
};

export type GetPersonalRecords401 = {
  error: string;
  code: string;
};

export type GetPersonalRecords500 = {
  error: string;
  code: string;
};

export type UpsertPersonalRecordBody = {
  /** @minLength 1 */
  exerciseName: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  reps: number;
};

/**
 * @nullable
 */
export type UpsertPersonalRecord204 =
  | (typeof UpsertPersonalRecord204)[keyof typeof UpsertPersonalRecord204]
  | null;

export const UpsertPersonalRecord204 = {} as const;

export type UpsertPersonalRecord401 = {
  error: string;
  code: string;
};

export type UpsertPersonalRecord500 = {
  error: string;
  code: string;
};

export type GetBodyProgressHistory200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
  loggedAt: string;
};

export type GetBodyProgressHistory401 = {
  error: string;
  code: string;
};

export type GetBodyProgressHistory500 = {
  error: string;
  code: string;
};

export type LogBodyProgressBody = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  age: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  bodyFatPercentage: number;
};

/**
 * @nullable
 */
export type LogBodyProgress204 =
  | (typeof LogBodyProgress204)[keyof typeof LogBodyProgress204]
  | null;

export const LogBodyProgress204 = {} as const;

export type LogBodyProgress401 = {
  error: string;
  code: string;
};

export type LogBodyProgress500 = {
  error: string;
  code: string;
};

export type GetRankingParams = {
  sortBy?: GetRankingSortBy;
};

export type GetRankingSortBy =
  (typeof GetRankingSortBy)[keyof typeof GetRankingSortBy];

export const GetRankingSortBy = {
  STREAK: "STREAK",
  XP: "XP",
} as const;

export type GetRanking200RankingItem = {
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
  streak: number;
  xp: number;
  level: number;
};

export type GetRanking200 = {
  ranking: GetRanking200RankingItem[];
  /** @nullable */
  currentUserPosition: number | null;
};

export type GetRanking401 = {
  error: string;
  code: string;
};

export type GetRanking500 = {
  error: string;
  code: string;
};

/**
 * @summary Get all workout plans
 */
export type getWorkoutPlansResponse200 = {
  data: GetWorkoutPlans200Item[];
  status: 200;
};

export type getWorkoutPlansResponse401 = {
  data: GetWorkoutPlans401;
  status: 401;
};

export type getWorkoutPlansResponse500 = {
  data: GetWorkoutPlans500;
  status: 500;
};

export type getWorkoutPlansResponseSuccess = getWorkoutPlansResponse200 & {
  headers: Headers;
};
export type getWorkoutPlansResponseError = (
  | getWorkoutPlansResponse401
  | getWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlansResponse =
  | getWorkoutPlansResponseSuccess
  | getWorkoutPlansResponseError;

export const getGetWorkoutPlansUrl = (params?: GetWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/?${stringifiedParams}`
    : `/workout-plans/`;
};

export const getWorkoutPlans = async (
  params?: GetWorkoutPlansParams,
  options?: RequestInit,
): Promise<getWorkoutPlansResponse> => {
  return customFetch<getWorkoutPlansResponse>(getGetWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Get workout day by id
 */
export type getWorkoutDayByIdResponse200 = {
  data: GetWorkoutDayById200;
  status: 200;
};

export type getWorkoutDayByIdResponse401 = {
  data: GetWorkoutDayById401;
  status: 401;
};

export type getWorkoutDayByIdResponse403 = {
  data: GetWorkoutDayById403;
  status: 403;
};

export type getWorkoutDayByIdResponse404 = {
  data: GetWorkoutDayById404;
  status: 404;
};

export type getWorkoutDayByIdResponse500 = {
  data: GetWorkoutDayById500;
  status: 500;
};

export type getWorkoutDayByIdResponseSuccess = getWorkoutDayByIdResponse200 & {
  headers: Headers;
};
export type getWorkoutDayByIdResponseError = (
  | getWorkoutDayByIdResponse401
  | getWorkoutDayByIdResponse403
  | getWorkoutDayByIdResponse404
  | getWorkoutDayByIdResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayByIdResponse =
  | getWorkoutDayByIdResponseSuccess
  | getWorkoutDayByIdResponseError;

export const getGetWorkoutDayByIdUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDayById = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayByIdResponse> => {
  return customFetch<getWorkoutDayByIdResponse>(
    getGetWorkoutDayByIdUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get workout plan by id
 */
export type getWorkoutPlanByIdResponse200 = {
  data: GetWorkoutPlanById200;
  status: 200;
};

export type getWorkoutPlanByIdResponse401 = {
  data: GetWorkoutPlanById401;
  status: 401;
};

export type getWorkoutPlanByIdResponse403 = {
  data: GetWorkoutPlanById403;
  status: 403;
};

export type getWorkoutPlanByIdResponse404 = {
  data: GetWorkoutPlanById404;
  status: 404;
};

export type getWorkoutPlanByIdResponse500 = {
  data: GetWorkoutPlanById500;
  status: 500;
};

export type getWorkoutPlanByIdResponseSuccess =
  getWorkoutPlanByIdResponse200 & {
    headers: Headers;
  };
export type getWorkoutPlanByIdResponseError = (
  | getWorkoutPlanByIdResponse401
  | getWorkoutPlanByIdResponse403
  | getWorkoutPlanByIdResponse404
  | getWorkoutPlanByIdResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanByIdResponse =
  | getWorkoutPlanByIdResponseSuccess
  | getWorkoutPlanByIdResponseError;

export const getGetWorkoutPlanByIdUrl = (id: string) => {
  return `/workout-plans/${id}`;
};

export const getWorkoutPlanById = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkoutPlanByIdResponse> => {
  return customFetch<getWorkoutPlanByIdResponse>(getGetWorkoutPlanByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse400 = {
  data: StartWorkoutSession400;
  status: 400;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse403 = {
  data: StartWorkoutSession403;
  status: 403;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse400
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse403
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a workout session
 */
export type completeWorkoutSessionResponse200 = {
  data: CompleteWorkoutSession200;
  status: 200;
};

export type completeWorkoutSessionResponse400 = {
  data: CompleteWorkoutSession400;
  status: 400;
};

export type completeWorkoutSessionResponse401 = {
  data: CompleteWorkoutSession401;
  status: 401;
};

export type completeWorkoutSessionResponse403 = {
  data: CompleteWorkoutSession403;
  status: 403;
};

export type completeWorkoutSessionResponse404 = {
  data: CompleteWorkoutSession404;
  status: 404;
};

export type completeWorkoutSessionResponse409 = {
  data: CompleteWorkoutSession409;
  status: 409;
};

export type completeWorkoutSessionResponse500 = {
  data: CompleteWorkoutSession500;
  status: 500;
};

export type completeWorkoutSessionResponseSuccess =
  completeWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type completeWorkoutSessionResponseError = (
  | completeWorkoutSessionResponse400
  | completeWorkoutSessionResponse401
  | completeWorkoutSessionResponse403
  | completeWorkoutSessionResponse404
  | completeWorkoutSessionResponse409
  | completeWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type completeWorkoutSessionResponse =
  | completeWorkoutSessionResponseSuccess
  | completeWorkoutSessionResponseError;

export const getCompleteWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const completeWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  completeWorkoutSessionBody: CompleteWorkoutSessionBody,
  options?: RequestInit,
): Promise<completeWorkoutSessionResponse> => {
  return customFetch<completeWorkoutSessionResponse>(
    getCompleteWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(completeWorkoutSessionBody),
    },
  );
};

/**
 * @summary Log or update a workout set
 */
export type upsertWorkoutSetResponse204 = {
  data: UpsertWorkoutSet204;
  status: 204;
};

export type upsertWorkoutSetResponse401 = {
  data: UpsertWorkoutSet401;
  status: 401;
};

export type upsertWorkoutSetResponse404 = {
  data: UpsertWorkoutSet404;
  status: 404;
};

export type upsertWorkoutSetResponse500 = {
  data: UpsertWorkoutSet500;
  status: 500;
};

export type upsertWorkoutSetResponseSuccess = upsertWorkoutSetResponse204 & {
  headers: Headers;
};
export type upsertWorkoutSetResponseError = (
  | upsertWorkoutSetResponse401
  | upsertWorkoutSetResponse404
  | upsertWorkoutSetResponse500
) & {
  headers: Headers;
};

export type upsertWorkoutSetResponse =
  | upsertWorkoutSetResponseSuccess
  | upsertWorkoutSetResponseError;

export const getUpsertWorkoutSetUrl = (
  sessionId: string,
  exerciseId: string,
  setIndex: number,
) => {
  return `/workout-plans/sessions/${sessionId}/exercises/${exerciseId}/sets/${setIndex}`;
};

export const upsertWorkoutSet = async (
  sessionId: string,
  exerciseId: string,
  setIndex: number,
  upsertWorkoutSetBody: UpsertWorkoutSetBody,
  options?: RequestInit,
): Promise<upsertWorkoutSetResponse> => {
  return customFetch<upsertWorkoutSetResponse>(
    getUpsertWorkoutSetUrl(sessionId, exerciseId, setIndex),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(upsertWorkoutSetBody),
    },
  );
};

/**
 * @summary Get the last log for a specific exercise
 */
export type getWorkoutExerciseHistoryResponse200 = {
  data: GetWorkoutExerciseHistory200;
  status: 200;
};

export type getWorkoutExerciseHistoryResponse401 = {
  data: GetWorkoutExerciseHistory401;
  status: 401;
};

export type getWorkoutExerciseHistoryResponse500 = {
  data: GetWorkoutExerciseHistory500;
  status: 500;
};

export type getWorkoutExerciseHistoryResponseSuccess =
  getWorkoutExerciseHistoryResponse200 & {
    headers: Headers;
  };
export type getWorkoutExerciseHistoryResponseError = (
  | getWorkoutExerciseHistoryResponse401
  | getWorkoutExerciseHistoryResponse500
) & {
  headers: Headers;
};

export type getWorkoutExerciseHistoryResponse =
  | getWorkoutExerciseHistoryResponseSuccess
  | getWorkoutExerciseHistoryResponseError;

export const getGetWorkoutExerciseHistoryUrl = (exerciseId: string) => {
  return `/workout-plans/exercises/${exerciseId}/history`;
};

export const getWorkoutExerciseHistory = async (
  exerciseId: string,
  options?: RequestInit,
): Promise<getWorkoutExerciseHistoryResponse> => {
  return customFetch<getWorkoutExerciseHistoryResponse>(
    getGetWorkoutExerciseHistoryUrl(exerciseId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user workout stats
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get my user data and friend code
 */
export type getMeResponse200 = {
  data: GetMe200;
  status: 200;
};

export type getMeResponse401 = {
  data: GetMe401;
  status: 401;
};

export type getMeResponse404 = {
  data: GetMe404;
  status: 404;
};

export type getMeResponse500 = {
  data: GetMe500;
  status: 500;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = (
  | getMeResponse401
  | getMeResponse404
  | getMeResponse500
) & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/friendships/me`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get friends list
 */
export type getFriendsResponse200 = {
  data: GetFriends200Item[];
  status: 200;
};

export type getFriendsResponse401 = {
  data: GetFriends401;
  status: 401;
};

export type getFriendsResponse500 = {
  data: GetFriends500;
  status: 500;
};

export type getFriendsResponseSuccess = getFriendsResponse200 & {
  headers: Headers;
};
export type getFriendsResponseError = (
  | getFriendsResponse401
  | getFriendsResponse500
) & {
  headers: Headers;
};

export type getFriendsResponse =
  | getFriendsResponseSuccess
  | getFriendsResponseError;

export const getGetFriendsUrl = () => {
  return `/friendships/`;
};

export const getFriends = async (
  options?: RequestInit,
): Promise<getFriendsResponse> => {
  return customFetch<getFriendsResponse>(getGetFriendsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Send a friend request by code or email
 */
export type addFriendResponse200 = {
  data: AddFriend200;
  status: 200;
};

export type addFriendResponse400 = {
  data: AddFriend400;
  status: 400;
};

export type addFriendResponse401 = {
  data: AddFriend401;
  status: 401;
};

export type addFriendResponse404 = {
  data: AddFriend404;
  status: 404;
};

export type addFriendResponse500 = {
  data: AddFriend500;
  status: 500;
};

export type addFriendResponseSuccess = addFriendResponse200 & {
  headers: Headers;
};
export type addFriendResponseError = (
  | addFriendResponse400
  | addFriendResponse401
  | addFriendResponse404
  | addFriendResponse500
) & {
  headers: Headers;
};

export type addFriendResponse =
  | addFriendResponseSuccess
  | addFriendResponseError;

export const getAddFriendUrl = () => {
  return `/friendships/`;
};

export const addFriend = async (
  addFriendBody: AddFriendBody,
  options?: RequestInit,
): Promise<addFriendResponse> => {
  return customFetch<addFriendResponse>(getAddFriendUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addFriendBody),
  });
};

/**
 * @summary Get pending friend requests
 */
export type getFriendRequestsResponse200 = {
  data: GetFriendRequests200Item[];
  status: 200;
};

export type getFriendRequestsResponse401 = {
  data: GetFriendRequests401;
  status: 401;
};

export type getFriendRequestsResponse500 = {
  data: GetFriendRequests500;
  status: 500;
};

export type getFriendRequestsResponseSuccess = getFriendRequestsResponse200 & {
  headers: Headers;
};
export type getFriendRequestsResponseError = (
  | getFriendRequestsResponse401
  | getFriendRequestsResponse500
) & {
  headers: Headers;
};

export type getFriendRequestsResponse =
  | getFriendRequestsResponseSuccess
  | getFriendRequestsResponseError;

export const getGetFriendRequestsUrl = (params?: GetFriendRequestsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/friendships/requests?${stringifiedParams}`
    : `/friendships/requests`;
};

export const getFriendRequests = async (
  params?: GetFriendRequestsParams,
  options?: RequestInit,
): Promise<getFriendRequestsResponse> => {
  return customFetch<getFriendRequestsResponse>(
    getGetFriendRequestsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Accept a friend request
 */
export type acceptFriendRequestResponse204 = {
  data: AcceptFriendRequest204;
  status: 204;
};

export type acceptFriendRequestResponse401 = {
  data: AcceptFriendRequest401;
  status: 401;
};

export type acceptFriendRequestResponse404 = {
  data: AcceptFriendRequest404;
  status: 404;
};

export type acceptFriendRequestResponse500 = {
  data: AcceptFriendRequest500;
  status: 500;
};

export type acceptFriendRequestResponseSuccess =
  acceptFriendRequestResponse204 & {
    headers: Headers;
  };
export type acceptFriendRequestResponseError = (
  | acceptFriendRequestResponse401
  | acceptFriendRequestResponse404
  | acceptFriendRequestResponse500
) & {
  headers: Headers;
};

export type acceptFriendRequestResponse =
  | acceptFriendRequestResponseSuccess
  | acceptFriendRequestResponseError;

export const getAcceptFriendRequestUrl = (id: string) => {
  return `/friendships/requests/${id}/accept`;
};

export const acceptFriendRequest = async (
  id: string,
  options?: RequestInit,
): Promise<acceptFriendRequestResponse> => {
  return customFetch<acceptFriendRequestResponse>(
    getAcceptFriendRequestUrl(id),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Decline or cancel a friend request
 */
export type declineFriendRequestResponse204 = {
  data: DeclineFriendRequest204;
  status: 204;
};

export type declineFriendRequestResponse401 = {
  data: DeclineFriendRequest401;
  status: 401;
};

export type declineFriendRequestResponse404 = {
  data: DeclineFriendRequest404;
  status: 404;
};

export type declineFriendRequestResponse500 = {
  data: DeclineFriendRequest500;
  status: 500;
};

export type declineFriendRequestResponseSuccess =
  declineFriendRequestResponse204 & {
    headers: Headers;
  };
export type declineFriendRequestResponseError = (
  | declineFriendRequestResponse401
  | declineFriendRequestResponse404
  | declineFriendRequestResponse500
) & {
  headers: Headers;
};

export type declineFriendRequestResponse =
  | declineFriendRequestResponseSuccess
  | declineFriendRequestResponseError;

export const getDeclineFriendRequestUrl = (id: string) => {
  return `/friendships/requests/${id}/decline`;
};

export const declineFriendRequest = async (
  id: string,
  options?: RequestInit,
): Promise<declineFriendRequestResponse> => {
  return customFetch<declineFriendRequestResponse>(
    getDeclineFriendRequestUrl(id),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Get activities feed
 */
export type getFeedResponse200 = {
  data: GetFeed200;
  status: 200;
};

export type getFeedResponse401 = {
  data: GetFeed401;
  status: 401;
};

export type getFeedResponse500 = {
  data: GetFeed500;
  status: 500;
};

export type getFeedResponseSuccess = getFeedResponse200 & {
  headers: Headers;
};
export type getFeedResponseError = (getFeedResponse401 | getFeedResponse500) & {
  headers: Headers;
};

export type getFeedResponse = getFeedResponseSuccess | getFeedResponseError;

export const getGetFeedUrl = (params?: GetFeedParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/feed/?${stringifiedParams}`
    : `/feed/`;
};

export const getFeed = async (
  params?: GetFeedParams,
  options?: RequestInit,
): Promise<getFeedResponse> => {
  return customFetch<getFeedResponse>(getGetFeedUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get activities feed for a specific user
 */
export type getUserFeedResponse200 = {
  data: GetUserFeed200;
  status: 200;
};

export type getUserFeedResponse401 = {
  data: GetUserFeed401;
  status: 401;
};

export type getUserFeedResponse403 = {
  data: GetUserFeed403;
  status: 403;
};

export type getUserFeedResponse500 = {
  data: GetUserFeed500;
  status: 500;
};

export type getUserFeedResponseSuccess = getUserFeedResponse200 & {
  headers: Headers;
};
export type getUserFeedResponseError = (
  | getUserFeedResponse401
  | getUserFeedResponse403
  | getUserFeedResponse500
) & {
  headers: Headers;
};

export type getUserFeedResponse =
  | getUserFeedResponseSuccess
  | getUserFeedResponseError;

export const getGetUserFeedUrl = (
  userId: string,
  params?: GetUserFeedParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/feed/users/${userId}?${stringifiedParams}`
    : `/feed/users/${userId}`;
};

export const getUserFeed = async (
  userId: string,
  params?: GetUserFeedParams,
  options?: RequestInit,
): Promise<getUserFeedResponse> => {
  return customFetch<getUserFeedResponse>(getGetUserFeedUrl(userId, params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Toggle powerup on an activity
 */
export type togglePowerupResponse204 = {
  data: TogglePowerup204;
  status: 204;
};

export type togglePowerupResponse401 = {
  data: TogglePowerup401;
  status: 401;
};

export type togglePowerupResponse403 = {
  data: TogglePowerup403;
  status: 403;
};

export type togglePowerupResponse404 = {
  data: TogglePowerup404;
  status: 404;
};

export type togglePowerupResponse500 = {
  data: TogglePowerup500;
  status: 500;
};

export type togglePowerupResponseSuccess = togglePowerupResponse204 & {
  headers: Headers;
};
export type togglePowerupResponseError = (
  | togglePowerupResponse401
  | togglePowerupResponse403
  | togglePowerupResponse404
  | togglePowerupResponse500
) & {
  headers: Headers;
};

export type togglePowerupResponse =
  | togglePowerupResponseSuccess
  | togglePowerupResponseError;

export const getTogglePowerupUrl = (id: string) => {
  return `/feed/activities/${id}/powerup`;
};

export const togglePowerup = async (
  id: string,
  options?: RequestInit,
): Promise<togglePowerupResponse> => {
  return customFetch<togglePowerupResponse>(getTogglePowerupUrl(id), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Add a comment to an activity
 */
export type addCommentResponse204 = {
  data: AddComment204;
  status: 204;
};

export type addCommentResponse401 = {
  data: AddComment401;
  status: 401;
};

export type addCommentResponse404 = {
  data: AddComment404;
  status: 404;
};

export type addCommentResponse500 = {
  data: AddComment500;
  status: 500;
};

export type addCommentResponseSuccess = addCommentResponse204 & {
  headers: Headers;
};
export type addCommentResponseError = (
  | addCommentResponse401
  | addCommentResponse404
  | addCommentResponse500
) & {
  headers: Headers;
};

export type addCommentResponse =
  | addCommentResponseSuccess
  | addCommentResponseError;

export const getAddCommentUrl = (id: string) => {
  return `/feed/activities/${id}/comments`;
};

export const addComment = async (
  id: string,
  addCommentBody: AddCommentBody,
  options?: RequestInit,
): Promise<addCommentResponse> => {
  return customFetch<addCommentResponse>(getAddCommentUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addCommentBody),
  });
};

/**
 * @summary Delete an activity
 */
export type deleteActivityResponse204 = {
  data: DeleteActivity204;
  status: 204;
};

export type deleteActivityResponse401 = {
  data: DeleteActivity401;
  status: 401;
};

export type deleteActivityResponse403 = {
  data: DeleteActivity403;
  status: 403;
};

export type deleteActivityResponse404 = {
  data: DeleteActivity404;
  status: 404;
};

export type deleteActivityResponse500 = {
  data: DeleteActivity500;
  status: 500;
};

export type deleteActivityResponseSuccess = deleteActivityResponse204 & {
  headers: Headers;
};
export type deleteActivityResponseError = (
  | deleteActivityResponse401
  | deleteActivityResponse403
  | deleteActivityResponse404
  | deleteActivityResponse500
) & {
  headers: Headers;
};

export type deleteActivityResponse =
  | deleteActivityResponseSuccess
  | deleteActivityResponseError;

export const getDeleteActivityUrl = (id: string) => {
  return `/feed/activities/${id}`;
};

export const deleteActivity = async (
  id: string,
  options?: RequestInit,
): Promise<deleteActivityResponse> => {
  return customFetch<deleteActivityResponse>(getDeleteActivityUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export type getNotificationsStreamResponse200 = {
  data: void;
  status: 200;
};

export type getNotificationsStreamResponseSuccess =
  getNotificationsStreamResponse200 & {
    headers: Headers;
  };
export type getNotificationsStreamResponse =
  getNotificationsStreamResponseSuccess;

export const getGetNotificationsStreamUrl = () => {
  return `/notifications/stream`;
};

export const getNotificationsStream = async (
  options?: RequestInit,
): Promise<getNotificationsStreamResponse> => {
  return customFetch<getNotificationsStreamResponse>(
    getGetNotificationsStreamUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get my notifications
 */
export type getNotificationsResponse200 = {
  data: GetNotifications200;
  status: 200;
};

export type getNotificationsResponse401 = {
  data: GetNotifications401;
  status: 401;
};

export type getNotificationsResponse500 = {
  data: GetNotifications500;
  status: 500;
};

export type getNotificationsResponseSuccess = getNotificationsResponse200 & {
  headers: Headers;
};
export type getNotificationsResponseError = (
  | getNotificationsResponse401
  | getNotificationsResponse500
) & {
  headers: Headers;
};

export type getNotificationsResponse =
  | getNotificationsResponseSuccess
  | getNotificationsResponseError;

export const getGetNotificationsUrl = (params?: GetNotificationsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/notifications/?${stringifiedParams}`
    : `/notifications/`;
};

export const getNotifications = async (
  params?: GetNotificationsParams,
  options?: RequestInit,
): Promise<getNotificationsResponse> => {
  return customFetch<getNotificationsResponse>(getGetNotificationsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Mark all my notifications as read
 */
export type markAllNotificationsAsReadResponse204 = {
  data: MarkAllNotificationsAsRead204;
  status: 204;
};

export type markAllNotificationsAsReadResponse401 = {
  data: MarkAllNotificationsAsRead401;
  status: 401;
};

export type markAllNotificationsAsReadResponse500 = {
  data: MarkAllNotificationsAsRead500;
  status: 500;
};

export type markAllNotificationsAsReadResponseSuccess =
  markAllNotificationsAsReadResponse204 & {
    headers: Headers;
  };
export type markAllNotificationsAsReadResponseError = (
  | markAllNotificationsAsReadResponse401
  | markAllNotificationsAsReadResponse500
) & {
  headers: Headers;
};

export type markAllNotificationsAsReadResponse =
  | markAllNotificationsAsReadResponseSuccess
  | markAllNotificationsAsReadResponseError;

export const getMarkAllNotificationsAsReadUrl = () => {
  return `/notifications/read-all`;
};

export const markAllNotificationsAsRead = async (
  options?: RequestInit,
): Promise<markAllNotificationsAsReadResponse> => {
  return customFetch<markAllNotificationsAsReadResponse>(
    getMarkAllNotificationsAsReadUrl(),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Mark a notification as read
 */
export type markNotificationAsReadResponse204 = {
  data: MarkNotificationAsRead204;
  status: 204;
};

export type markNotificationAsReadResponse401 = {
  data: MarkNotificationAsRead401;
  status: 401;
};

export type markNotificationAsReadResponse404 = {
  data: MarkNotificationAsRead404;
  status: 404;
};

export type markNotificationAsReadResponse500 = {
  data: MarkNotificationAsRead500;
  status: 500;
};

export type markNotificationAsReadResponseSuccess =
  markNotificationAsReadResponse204 & {
    headers: Headers;
  };
export type markNotificationAsReadResponseError = (
  | markNotificationAsReadResponse401
  | markNotificationAsReadResponse404
  | markNotificationAsReadResponse500
) & {
  headers: Headers;
};

export type markNotificationAsReadResponse =
  | markNotificationAsReadResponseSuccess
  | markNotificationAsReadResponseError;

export const getMarkNotificationAsReadUrl = (id: string) => {
  return `/notifications/${id}/read`;
};

export const markNotificationAsRead = async (
  id: string,
  options?: RequestInit,
): Promise<markNotificationAsReadResponse> => {
  return customFetch<markNotificationAsReadResponse>(
    getMarkNotificationAsReadUrl(id),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Get all achievements and user progress
 */
export type getAchievementsResponse200 = {
  data: GetAchievements200Item[];
  status: 200;
};

export type getAchievementsResponse401 = {
  data: GetAchievements401;
  status: 401;
};

export type getAchievementsResponse500 = {
  data: GetAchievements500;
  status: 500;
};

export type getAchievementsResponseSuccess = getAchievementsResponse200 & {
  headers: Headers;
};
export type getAchievementsResponseError = (
  | getAchievementsResponse401
  | getAchievementsResponse500
) & {
  headers: Headers;
};

export type getAchievementsResponse =
  | getAchievementsResponseSuccess
  | getAchievementsResponseError;

export const getGetAchievementsUrl = () => {
  return `/gamification/achievements`;
};

export const getAchievements = async (
  options?: RequestInit,
): Promise<getAchievementsResponse> => {
  return customFetch<getAchievementsResponse>(getGetAchievementsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get available challenges
 */
export type getChallengesResponse200 = {
  data: GetChallenges200Item[];
  status: 200;
};

export type getChallengesResponse401 = {
  data: GetChallenges401;
  status: 401;
};

export type getChallengesResponse500 = {
  data: GetChallenges500;
  status: 500;
};

export type getChallengesResponseSuccess = getChallengesResponse200 & {
  headers: Headers;
};
export type getChallengesResponseError = (
  | getChallengesResponse401
  | getChallengesResponse500
) & {
  headers: Headers;
};

export type getChallengesResponse =
  | getChallengesResponseSuccess
  | getChallengesResponseError;

export const getGetChallengesUrl = () => {
  return `/gamification/challenges`;
};

export const getChallenges = async (
  options?: RequestInit,
): Promise<getChallengesResponse> => {
  return customFetch<getChallengesResponse>(getGetChallengesUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Join a challenge
 */
export type joinChallengeResponse204 = {
  data: JoinChallenge204;
  status: 204;
};

export type joinChallengeResponse401 = {
  data: JoinChallenge401;
  status: 401;
};

export type joinChallengeResponse404 = {
  data: JoinChallenge404;
  status: 404;
};

export type joinChallengeResponse500 = {
  data: JoinChallenge500;
  status: 500;
};

export type joinChallengeResponseSuccess = joinChallengeResponse204 & {
  headers: Headers;
};
export type joinChallengeResponseError = (
  | joinChallengeResponse401
  | joinChallengeResponse404
  | joinChallengeResponse500
) & {
  headers: Headers;
};

export type joinChallengeResponse =
  | joinChallengeResponseSuccess
  | joinChallengeResponseError;

export const getJoinChallengeUrl = (id: string) => {
  return `/gamification/challenges/${id}/join`;
};

export const joinChallenge = async (
  id: string,
  options?: RequestInit,
): Promise<joinChallengeResponse> => {
  return customFetch<joinChallengeResponse>(getJoinChallengeUrl(id), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Get XP transaction history
 */
export type getXpHistoryResponse200 = {
  data: GetXpHistory200Item[];
  status: 200;
};

export type getXpHistoryResponse401 = {
  data: GetXpHistory401;
  status: 401;
};

export type getXpHistoryResponse500 = {
  data: GetXpHistory500;
  status: 500;
};

export type getXpHistoryResponseSuccess = getXpHistoryResponse200 & {
  headers: Headers;
};
export type getXpHistoryResponseError = (
  | getXpHistoryResponse401
  | getXpHistoryResponse500
) & {
  headers: Headers;
};

export type getXpHistoryResponse =
  | getXpHistoryResponseSuccess
  | getXpHistoryResponseError;

export const getGetXpHistoryUrl = () => {
  return `/gamification/xp-history`;
};

export const getXpHistory = async (
  options?: RequestInit,
): Promise<getXpHistoryResponse> => {
  return customFetch<getXpHistoryResponse>(getGetXpHistoryUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Update my profile
 */
export type updateProfileResponse200 = {
  data: UpdateProfile200;
  status: 200;
};

export type updateProfileResponse401 = {
  data: UpdateProfile401;
  status: 401;
};

export type updateProfileResponse500 = {
  data: UpdateProfile500;
  status: 500;
};

export type updateProfileResponseSuccess = updateProfileResponse200 & {
  headers: Headers;
};
export type updateProfileResponseError = (
  | updateProfileResponse401
  | updateProfileResponse500
) & {
  headers: Headers;
};

export type updateProfileResponse =
  | updateProfileResponseSuccess
  | updateProfileResponseError;

export const getUpdateProfileUrl = () => {
  return `/me`;
};

export const updateProfile = async (
  updateProfileBody: UpdateProfileBody,
  options?: RequestInit,
): Promise<updateProfileResponse> => {
  return customFetch<updateProfileResponse>(getUpdateProfileUrl(), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProfileBody),
  });
};

/**
 * @summary Get user training data
 */
export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200;
  status: 200;
};

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401;
  status: 401;
};

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500;
  status: 500;
};

export type getUserTrainDataResponseSuccess = getUserTrainDataResponse200 & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (
  | getUserTrainDataResponse401
  | getUserTrainDataResponse500
) & {
  headers: Headers;
};

export type getUserTrainDataResponse =
  | getUserTrainDataResponseSuccess
  | getUserTrainDataResponseError;

export const getGetUserTrainDataUrl = () => {
  return `/me`;
};

export const getUserTrainData = async (
  options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Upsert user training data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200;
  status: 200;
};

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401;
  status: 401;
};

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500;
  status: 500;
};

export type upsertUserTrainDataResponseSuccess =
  upsertUserTrainDataResponse200 & {
    headers: Headers;
  };
export type upsertUserTrainDataResponseError = (
  | upsertUserTrainDataResponse401
  | upsertUserTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse =
  | upsertUserTrainDataResponseSuccess
  | upsertUserTrainDataResponseError;

export const getUpsertUserTrainDataUrl = () => {
  return `/me`;
};

export const upsertUserTrainData = async (
  upsertUserTrainDataBody: UpsertUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertUserTrainDataBody),
  });
};

/**
 * @summary Search for users
 */
export type searchUsersResponse200 = {
  data: SearchUsers200Item[];
  status: 200;
};

export type searchUsersResponse401 = {
  data: SearchUsers401;
  status: 401;
};

export type searchUsersResponse500 = {
  data: SearchUsers500;
  status: 500;
};

export type searchUsersResponseSuccess = searchUsersResponse200 & {
  headers: Headers;
};
export type searchUsersResponseError = (
  | searchUsersResponse401
  | searchUsersResponse500
) & {
  headers: Headers;
};

export type searchUsersResponse =
  | searchUsersResponseSuccess
  | searchUsersResponseError;

export const getSearchUsersUrl = (params: SearchUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/search?${stringifiedParams}`
    : `/search`;
};

export const searchUsers = async (
  params: SearchUsersParams,
  options?: RequestInit,
): Promise<searchUsersResponse> => {
  return customFetch<searchUsersResponse>(getSearchUsersUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get a user's public profile
 */
export type getUserProfileResponse200 = {
  data: GetUserProfile200;
  status: 200;
};

export type getUserProfileResponse401 = {
  data: GetUserProfile401;
  status: 401;
};

export type getUserProfileResponse403 = {
  data: GetUserProfile403;
  status: 403;
};

export type getUserProfileResponse404 = {
  data: GetUserProfile404;
  status: 404;
};

export type getUserProfileResponse500 = {
  data: GetUserProfile500;
  status: 500;
};

export type getUserProfileResponseSuccess = getUserProfileResponse200 & {
  headers: Headers;
};
export type getUserProfileResponseError = (
  | getUserProfileResponse401
  | getUserProfileResponse403
  | getUserProfileResponse404
  | getUserProfileResponse500
) & {
  headers: Headers;
};

export type getUserProfileResponse =
  | getUserProfileResponseSuccess
  | getUserProfileResponseError;

export const getGetUserProfileUrl = (userId: string) => {
  return `/profile/${userId}`;
};

export const getUserProfile = async (
  userId: string,
  options?: RequestInit,
): Promise<getUserProfileResponse> => {
  return customFetch<getUserProfileResponse>(getGetUserProfileUrl(userId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Update privacy settings
 */
export type updatePrivacySettingsResponse204 = {
  data: UpdatePrivacySettings204;
  status: 204;
};

export type updatePrivacySettingsResponse401 = {
  data: UpdatePrivacySettings401;
  status: 401;
};

export type updatePrivacySettingsResponse500 = {
  data: UpdatePrivacySettings500;
  status: 500;
};

export type updatePrivacySettingsResponseSuccess =
  updatePrivacySettingsResponse204 & {
    headers: Headers;
  };
export type updatePrivacySettingsResponseError = (
  | updatePrivacySettingsResponse401
  | updatePrivacySettingsResponse500
) & {
  headers: Headers;
};

export type updatePrivacySettingsResponse =
  | updatePrivacySettingsResponseSuccess
  | updatePrivacySettingsResponseError;

export const getUpdatePrivacySettingsUrl = () => {
  return `/me/privacy`;
};

export const updatePrivacySettings = async (
  updatePrivacySettingsBody: UpdatePrivacySettingsBody,
  options?: RequestInit,
): Promise<updatePrivacySettingsResponse> => {
  return customFetch<updatePrivacySettingsResponse>(
    getUpdatePrivacySettingsUrl(),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updatePrivacySettingsBody),
    },
  );
};

/**
 * @summary Get user personal records
 */
export type getPersonalRecordsResponse200 = {
  data: GetPersonalRecords200Item[];
  status: 200;
};

export type getPersonalRecordsResponse401 = {
  data: GetPersonalRecords401;
  status: 401;
};

export type getPersonalRecordsResponse500 = {
  data: GetPersonalRecords500;
  status: 500;
};

export type getPersonalRecordsResponseSuccess =
  getPersonalRecordsResponse200 & {
    headers: Headers;
  };
export type getPersonalRecordsResponseError = (
  | getPersonalRecordsResponse401
  | getPersonalRecordsResponse500
) & {
  headers: Headers;
};

export type getPersonalRecordsResponse =
  | getPersonalRecordsResponseSuccess
  | getPersonalRecordsResponseError;

export const getGetPersonalRecordsUrl = () => {
  return `/personal-records`;
};

export const getPersonalRecords = async (
  options?: RequestInit,
): Promise<getPersonalRecordsResponse> => {
  return customFetch<getPersonalRecordsResponse>(getGetPersonalRecordsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Upsert a personal record
 */
export type upsertPersonalRecordResponse204 = {
  data: UpsertPersonalRecord204;
  status: 204;
};

export type upsertPersonalRecordResponse401 = {
  data: UpsertPersonalRecord401;
  status: 401;
};

export type upsertPersonalRecordResponse500 = {
  data: UpsertPersonalRecord500;
  status: 500;
};

export type upsertPersonalRecordResponseSuccess =
  upsertPersonalRecordResponse204 & {
    headers: Headers;
  };
export type upsertPersonalRecordResponseError = (
  | upsertPersonalRecordResponse401
  | upsertPersonalRecordResponse500
) & {
  headers: Headers;
};

export type upsertPersonalRecordResponse =
  | upsertPersonalRecordResponseSuccess
  | upsertPersonalRecordResponseError;

export const getUpsertPersonalRecordUrl = () => {
  return `/personal-records`;
};

export const upsertPersonalRecord = async (
  upsertPersonalRecordBody: UpsertPersonalRecordBody,
  options?: RequestInit,
): Promise<upsertPersonalRecordResponse> => {
  return customFetch<upsertPersonalRecordResponse>(
    getUpsertPersonalRecordUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(upsertPersonalRecordBody),
    },
  );
};

/**
 * @summary Get body progress history
 */
export type getBodyProgressHistoryResponse200 = {
  data: GetBodyProgressHistory200Item[];
  status: 200;
};

export type getBodyProgressHistoryResponse401 = {
  data: GetBodyProgressHistory401;
  status: 401;
};

export type getBodyProgressHistoryResponse500 = {
  data: GetBodyProgressHistory500;
  status: 500;
};

export type getBodyProgressHistoryResponseSuccess =
  getBodyProgressHistoryResponse200 & {
    headers: Headers;
  };
export type getBodyProgressHistoryResponseError = (
  | getBodyProgressHistoryResponse401
  | getBodyProgressHistoryResponse500
) & {
  headers: Headers;
};

export type getBodyProgressHistoryResponse =
  | getBodyProgressHistoryResponseSuccess
  | getBodyProgressHistoryResponseError;

export const getGetBodyProgressHistoryUrl = () => {
  return `/body-progress`;
};

export const getBodyProgressHistory = async (
  options?: RequestInit,
): Promise<getBodyProgressHistoryResponse> => {
  return customFetch<getBodyProgressHistoryResponse>(
    getGetBodyProgressHistoryUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Log a new body progress entry
 */
export type logBodyProgressResponse204 = {
  data: LogBodyProgress204;
  status: 204;
};

export type logBodyProgressResponse401 = {
  data: LogBodyProgress401;
  status: 401;
};

export type logBodyProgressResponse500 = {
  data: LogBodyProgress500;
  status: 500;
};

export type logBodyProgressResponseSuccess = logBodyProgressResponse204 & {
  headers: Headers;
};
export type logBodyProgressResponseError = (
  | logBodyProgressResponse401
  | logBodyProgressResponse500
) & {
  headers: Headers;
};

export type logBodyProgressResponse =
  | logBodyProgressResponseSuccess
  | logBodyProgressResponseError;

export const getLogBodyProgressUrl = () => {
  return `/body-progress`;
};

export const logBodyProgress = async (
  logBodyProgressBody: LogBodyProgressBody,
  options?: RequestInit,
): Promise<logBodyProgressResponse> => {
  return customFetch<logBodyProgressResponse>(getLogBodyProgressUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(logBodyProgressBody),
  });
};

/**
 * @summary Get users ranking
 */
export type getRankingResponse200 = {
  data: GetRanking200;
  status: 200;
};

export type getRankingResponse401 = {
  data: GetRanking401;
  status: 401;
};

export type getRankingResponse500 = {
  data: GetRanking500;
  status: 500;
};

export type getRankingResponseSuccess = getRankingResponse200 & {
  headers: Headers;
};
export type getRankingResponseError = (
  | getRankingResponse401
  | getRankingResponse500
) & {
  headers: Headers;
};

export type getRankingResponse =
  | getRankingResponseSuccess
  | getRankingResponseError;

export const getGetRankingUrl = (params?: GetRankingParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/ranking?${stringifiedParams}`
    : `/ranking`;
};

export const getRanking = async (
  params?: GetRankingParams,
  options?: RequestInit,
): Promise<getRankingResponse> => {
  return customFetch<getRankingResponse>(getGetRankingUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Chat with AI personal trainer
 */
export type aiChatResponse200 = {
  data: void;
  status: 200;
};

export type aiChatResponseSuccess = aiChatResponse200 & {
  headers: Headers;
};
export type aiChatResponse = aiChatResponseSuccess;

export const getAiChatUrl = () => {
  return `/ai/`;
};

export const aiChat = async (
  options?: RequestInit,
): Promise<aiChatResponse> => {
  return customFetch<aiChatResponse>(getAiChatUrl(), {
    ...options,
    method: "POST",
  });
};
