/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Fit App API
 * Documentação da API do Fit App
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type GetWorkoutPlansParams = {
  active?: string;
};

export type GetWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const GetWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: GetWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRestDay: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type GetWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: GetWorkoutPlans200ItemWorkoutDaysItem[];
};

export type GetWorkoutPlans401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  /** @nullable */
  coverImageUrl?: string | null;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRestDay?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  /** @nullable */
  coverImageUrl?: string | null;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRestDay: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById200WeekDay =
  (typeof GetWorkoutDayById200WeekDay)[keyof typeof GetWorkoutDayById200WeekDay];

export const GetWorkoutDayById200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDayById200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutDayById200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @nullable */
  startedAt?: string | null;
  /** @nullable */
  completedAt?: string | null;
};

export type GetWorkoutDayById200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRestDay: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDayById200WeekDay;
  exercises: GetWorkoutDayById200ExercisesItem[];
  sessions: GetWorkoutDayById200SessionsItem[];
};

export type GetWorkoutDayById401 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById403 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById404 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlanById200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlanById200WorkoutDaysItemWeekDay];

export const GetWorkoutPlanById200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlanById200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlanById200WorkoutDaysItemWeekDay;
  name: string;
  isRestDay: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlanById200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlanById200WorkoutDaysItem[];
};

export type GetWorkoutPlanById401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById403 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
};

export type StartWorkoutSession400 = {
  error: string;
  code: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession403 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
};

export type CompleteWorkoutSession400 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession401 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession403 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession404 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession409 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | 00000000-0000-0000-0000-000000000000 | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRestDay: boolean;
  weekDay:
    | "MONDAY"
    | "TUESDAY"
    | "WEDNESDAY"
    | "THURSDAY"
    | "FRIDAY"
    | "SATURDAY"
    | "SUNDAY";
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercisesCount: number;
} | null;

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  activeWorkoutPlanId: string | null;
  /** @nullable */
  todayWorkoutDay: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  from: string;
  /**
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  age: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  age: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

/**
 * @summary Get all workout plans
 */
export type getWorkoutPlansResponse200 = {
  data: GetWorkoutPlans200Item[];
  status: 200;
};

export type getWorkoutPlansResponse401 = {
  data: GetWorkoutPlans401;
  status: 401;
};

export type getWorkoutPlansResponse500 = {
  data: GetWorkoutPlans500;
  status: 500;
};

export type getWorkoutPlansResponseSuccess = getWorkoutPlansResponse200 & {
  headers: Headers;
};
export type getWorkoutPlansResponseError = (
  | getWorkoutPlansResponse401
  | getWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlansResponse =
  | getWorkoutPlansResponseSuccess
  | getWorkoutPlansResponseError;

export const getGetWorkoutPlansUrl = (params?: GetWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/?${stringifiedParams}`
    : `/workout-plans/`;
};

export const getWorkoutPlans = async (
  params?: GetWorkoutPlansParams,
  options?: RequestInit,
): Promise<getWorkoutPlansResponse> => {
  return customFetch<getWorkoutPlansResponse>(getGetWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Get workout day by id
 */
export type getWorkoutDayByIdResponse200 = {
  data: GetWorkoutDayById200;
  status: 200;
};

export type getWorkoutDayByIdResponse401 = {
  data: GetWorkoutDayById401;
  status: 401;
};

export type getWorkoutDayByIdResponse403 = {
  data: GetWorkoutDayById403;
  status: 403;
};

export type getWorkoutDayByIdResponse404 = {
  data: GetWorkoutDayById404;
  status: 404;
};

export type getWorkoutDayByIdResponse500 = {
  data: GetWorkoutDayById500;
  status: 500;
};

export type getWorkoutDayByIdResponseSuccess = getWorkoutDayByIdResponse200 & {
  headers: Headers;
};
export type getWorkoutDayByIdResponseError = (
  | getWorkoutDayByIdResponse401
  | getWorkoutDayByIdResponse403
  | getWorkoutDayByIdResponse404
  | getWorkoutDayByIdResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayByIdResponse =
  | getWorkoutDayByIdResponseSuccess
  | getWorkoutDayByIdResponseError;

export const getGetWorkoutDayByIdUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDayById = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayByIdResponse> => {
  return customFetch<getWorkoutDayByIdResponse>(
    getGetWorkoutDayByIdUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get workout plan by id
 */
export type getWorkoutPlanByIdResponse200 = {
  data: GetWorkoutPlanById200;
  status: 200;
};

export type getWorkoutPlanByIdResponse401 = {
  data: GetWorkoutPlanById401;
  status: 401;
};

export type getWorkoutPlanByIdResponse403 = {
  data: GetWorkoutPlanById403;
  status: 403;
};

export type getWorkoutPlanByIdResponse404 = {
  data: GetWorkoutPlanById404;
  status: 404;
};

export type getWorkoutPlanByIdResponse500 = {
  data: GetWorkoutPlanById500;
  status: 500;
};

export type getWorkoutPlanByIdResponseSuccess =
  getWorkoutPlanByIdResponse200 & {
    headers: Headers;
  };
export type getWorkoutPlanByIdResponseError = (
  | getWorkoutPlanByIdResponse401
  | getWorkoutPlanByIdResponse403
  | getWorkoutPlanByIdResponse404
  | getWorkoutPlanByIdResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanByIdResponse =
  | getWorkoutPlanByIdResponseSuccess
  | getWorkoutPlanByIdResponseError;

export const getGetWorkoutPlanByIdUrl = (id: string) => {
  return `/workout-plans/${id}`;
};

export const getWorkoutPlanById = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkoutPlanByIdResponse> => {
  return customFetch<getWorkoutPlanByIdResponse>(getGetWorkoutPlanByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse400 = {
  data: StartWorkoutSession400;
  status: 400;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse403 = {
  data: StartWorkoutSession403;
  status: 403;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse400
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse403
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a workout session
 */
export type completeWorkoutSessionResponse200 = {
  data: CompleteWorkoutSession200;
  status: 200;
};

export type completeWorkoutSessionResponse400 = {
  data: CompleteWorkoutSession400;
  status: 400;
};

export type completeWorkoutSessionResponse401 = {
  data: CompleteWorkoutSession401;
  status: 401;
};

export type completeWorkoutSessionResponse403 = {
  data: CompleteWorkoutSession403;
  status: 403;
};

export type completeWorkoutSessionResponse404 = {
  data: CompleteWorkoutSession404;
  status: 404;
};

export type completeWorkoutSessionResponse409 = {
  data: CompleteWorkoutSession409;
  status: 409;
};

export type completeWorkoutSessionResponse500 = {
  data: CompleteWorkoutSession500;
  status: 500;
};

export type completeWorkoutSessionResponseSuccess =
  completeWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type completeWorkoutSessionResponseError = (
  | completeWorkoutSessionResponse400
  | completeWorkoutSessionResponse401
  | completeWorkoutSessionResponse403
  | completeWorkoutSessionResponse404
  | completeWorkoutSessionResponse409
  | completeWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type completeWorkoutSessionResponse =
  | completeWorkoutSessionResponseSuccess
  | completeWorkoutSessionResponseError;

export const getCompleteWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const completeWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  options?: RequestInit,
): Promise<completeWorkoutSessionResponse> => {
  return customFetch<completeWorkoutSessionResponse>(
    getCompleteWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user workout stats
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user training data
 */
export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200;
  status: 200;
};

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401;
  status: 401;
};

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500;
  status: 500;
};

export type getUserTrainDataResponseSuccess = getUserTrainDataResponse200 & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (
  | getUserTrainDataResponse401
  | getUserTrainDataResponse500
) & {
  headers: Headers;
};

export type getUserTrainDataResponse =
  | getUserTrainDataResponseSuccess
  | getUserTrainDataResponseError;

export const getGetUserTrainDataUrl = () => {
  return `/me`;
};

export const getUserTrainData = async (
  options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Upsert user training data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200;
  status: 200;
};

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401;
  status: 401;
};

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500;
  status: 500;
};

export type upsertUserTrainDataResponseSuccess =
  upsertUserTrainDataResponse200 & {
    headers: Headers;
  };
export type upsertUserTrainDataResponseError = (
  | upsertUserTrainDataResponse401
  | upsertUserTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse =
  | upsertUserTrainDataResponseSuccess
  | upsertUserTrainDataResponseError;

export const getUpsertUserTrainDataUrl = () => {
  return `/me`;
};

export const upsertUserTrainData = async (
  upsertUserTrainDataBody: UpsertUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertUserTrainDataBody),
  });
};

/**
 * @summary Chat with AI personal trainer
 */
export type aiChatResponse200 = {
  data: void;
  status: 200;
};

export type aiChatResponseSuccess = aiChatResponse200 & {
  headers: Headers;
};
export type aiChatResponse = aiChatResponseSuccess;

export const getAiChatUrl = () => {
  return `/ai/`;
};

export const aiChat = async (
  options?: RequestInit,
): Promise<aiChatResponse> => {
  return customFetch<aiChatResponse>(getAiChatUrl(), {
    ...options,
    method: "POST",
  });
};
