/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Fit App API
 * Documentação da API do Fit App
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type GetWorkoutPlansParams = {
  active?: string;
};

export type GetWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const GetWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: GetWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRestDay: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type GetWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: GetWorkoutPlans200ItemWorkoutDaysItem[];
};

export type GetWorkoutPlans401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  /** @nullable */
  coverImageUrl?: string | null;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRestDay?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  /** @nullable */
  coverImageUrl?: string | null;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRestDay: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById200WeekDay =
  (typeof GetWorkoutDayById200WeekDay)[keyof typeof GetWorkoutDayById200WeekDay];

export const GetWorkoutDayById200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDayById200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutDayById200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @nullable */
  startedAt?: string | null;
  /** @nullable */
  completedAt?: string | null;
};

export type GetWorkoutDayById200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRestDay: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDayById200WeekDay;
  exercises: GetWorkoutDayById200ExercisesItem[];
  sessions: GetWorkoutDayById200SessionsItem[];
};

export type GetWorkoutDayById401 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById403 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById404 = {
  error: string;
  code: string;
};

export type GetWorkoutDayById500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlanById200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlanById200WorkoutDaysItemWeekDay];

export const GetWorkoutPlanById200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlanById200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlanById200WorkoutDaysItemWeekDay;
  name: string;
  isRestDay: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlanById200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlanById200WorkoutDaysItem[];
};

export type GetWorkoutPlanById401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById403 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanById500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
};

export type StartWorkoutSession400 = {
  error: string;
  code: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession403 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSessionParams = {
  statusMessage?: string;
};

export type CompleteWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
};

export type CompleteWorkoutSession400 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession401 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession403 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession404 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession409 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | 00000000-0000-0000-0000-000000000000 | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRestDay: boolean;
  weekDay:
    | "MONDAY"
    | "TUESDAY"
    | "WEDNESDAY"
    | "THURSDAY"
    | "FRIDAY"
    | "SATURDAY"
    | "SUNDAY";
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercisesCount: number;
} | null;

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  activeWorkoutPlanId: string | null;
  /** @nullable */
  todayWorkoutDay: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  from: string;
  /**
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  completedRestDays: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

export type GetMe200 = {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  image: string | null;
  /** @nullable */
  friendCode: string | null;
};

export type GetMe401 = {
  error: string;
  code: string;
};

export type GetMe404 = {
  error: string;
  code: string;
};

export type GetMe500 = {
  error: string;
  code: string;
};

export type GetFriends200Item = {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  image: string | null;
  /** @nullable */
  friendCode: string | null;
  since: string;
};

export type GetFriends401 = {
  error: string;
  code: string;
};

export type GetFriends500 = {
  error: string;
  code: string;
};

export type AddFriendBody = {
  /** @minLength 1 */
  codeOrEmail: string;
};

export type AddFriend200 = {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  image: string | null;
  /** @nullable */
  friendCode: string | null;
};

export type AddFriend400 = {
  error: string;
  code: string;
};

export type AddFriend401 = {
  error: string;
  code: string;
};

export type AddFriend404 = {
  error: string;
  code: string;
};

export type AddFriend500 = {
  error: string;
  code: string;
};

export type GetFriendRequests200ItemStatus =
  (typeof GetFriendRequests200ItemStatus)[keyof typeof GetFriendRequests200ItemStatus];

export const GetFriendRequests200ItemStatus = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
} as const;

export type GetFriendRequests200ItemUser = {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  image: string | null;
};

export type GetFriendRequests200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  status: GetFriendRequests200ItemStatus;
  createdAt: string;
  user: GetFriendRequests200ItemUser;
};

export type GetFriendRequests401 = {
  error: string;
  code: string;
};

export type GetFriendRequests500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type AcceptFriendRequest204 =
  | (typeof AcceptFriendRequest204)[keyof typeof AcceptFriendRequest204]
  | null;

export const AcceptFriendRequest204 = {} as const;

export type AcceptFriendRequest401 = {
  error: string;
  code: string;
};

export type AcceptFriendRequest404 = {
  error: string;
  code: string;
};

export type AcceptFriendRequest500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type DeclineFriendRequest204 =
  | (typeof DeclineFriendRequest204)[keyof typeof DeclineFriendRequest204]
  | null;

export const DeclineFriendRequest204 = {} as const;

export type DeclineFriendRequest401 = {
  error: string;
  code: string;
};

export type DeclineFriendRequest404 = {
  error: string;
  code: string;
};

export type DeclineFriendRequest500 = {
  error: string;
  code: string;
};

export type GetFeed200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
  userName: string;
  /** @nullable */
  userImage: string | null;
  workoutDayName: string;
  workoutPlanName: string;
  /** @nullable */
  statusMessage: string | null;
  /** @nullable */
  imageUrl: string | null;
  startedAt: string;
  completedAt: string;
  powerupsCount: number;
  hasPowerupByMe: boolean;
  createdAt: string;
};

export type GetFeed401 = {
  error: string;
  code: string;
};

export type GetFeed500 = {
  error: string;
  code: string;
};

export type GetUserFeed200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
  userName: string;
  /** @nullable */
  userImage: string | null;
  workoutDayName: string;
  workoutPlanName: string;
  /** @nullable */
  statusMessage: string | null;
  /** @nullable */
  imageUrl: string | null;
  startedAt: string;
  completedAt: string;
  powerupsCount: number;
  hasPowerupByMe: boolean;
  createdAt: string;
};

export type GetUserFeed401 = {
  error: string;
  code: string;
};

export type GetUserFeed403 = {
  error: string;
  code: string;
};

export type GetUserFeed500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type TogglePowerup204 =
  | (typeof TogglePowerup204)[keyof typeof TogglePowerup204]
  | null;

export const TogglePowerup204 = {} as const;

export type TogglePowerup401 = {
  error: string;
  code: string;
};

export type TogglePowerup403 = {
  error: string;
  code: string;
};

export type TogglePowerup404 = {
  error: string;
  code: string;
};

export type TogglePowerup500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type DeleteActivity204 =
  | (typeof DeleteActivity204)[keyof typeof DeleteActivity204]
  | null;

export const DeleteActivity204 = {} as const;

export type DeleteActivity401 = {
  error: string;
  code: string;
};

export type DeleteActivity403 = {
  error: string;
  code: string;
};

export type DeleteActivity404 = {
  error: string;
  code: string;
};

export type DeleteActivity500 = {
  error: string;
  code: string;
};

export type GetStreakRanking200RankingItem = {
  id: string;
  name: string;
  /** @nullable */
  image: string | null;
  streak: number;
};

export type GetStreakRanking200 = {
  ranking: GetStreakRanking200RankingItem[];
  /** @nullable */
  currentUserPosition: number | null;
};

export type GetStreakRanking401 = {
  error: string;
  code: string;
};

export type GetStreakRanking500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  age: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  age: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

/**
 * @summary Get all workout plans
 */
export type getWorkoutPlansResponse200 = {
  data: GetWorkoutPlans200Item[];
  status: 200;
};

export type getWorkoutPlansResponse401 = {
  data: GetWorkoutPlans401;
  status: 401;
};

export type getWorkoutPlansResponse500 = {
  data: GetWorkoutPlans500;
  status: 500;
};

export type getWorkoutPlansResponseSuccess = getWorkoutPlansResponse200 & {
  headers: Headers;
};
export type getWorkoutPlansResponseError = (
  | getWorkoutPlansResponse401
  | getWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlansResponse =
  | getWorkoutPlansResponseSuccess
  | getWorkoutPlansResponseError;

export const getGetWorkoutPlansUrl = (params?: GetWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/?${stringifiedParams}`
    : `/workout-plans/`;
};

export const getWorkoutPlans = async (
  params?: GetWorkoutPlansParams,
  options?: RequestInit,
): Promise<getWorkoutPlansResponse> => {
  return customFetch<getWorkoutPlansResponse>(getGetWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Get workout day by id
 */
export type getWorkoutDayByIdResponse200 = {
  data: GetWorkoutDayById200;
  status: 200;
};

export type getWorkoutDayByIdResponse401 = {
  data: GetWorkoutDayById401;
  status: 401;
};

export type getWorkoutDayByIdResponse403 = {
  data: GetWorkoutDayById403;
  status: 403;
};

export type getWorkoutDayByIdResponse404 = {
  data: GetWorkoutDayById404;
  status: 404;
};

export type getWorkoutDayByIdResponse500 = {
  data: GetWorkoutDayById500;
  status: 500;
};

export type getWorkoutDayByIdResponseSuccess = getWorkoutDayByIdResponse200 & {
  headers: Headers;
};
export type getWorkoutDayByIdResponseError = (
  | getWorkoutDayByIdResponse401
  | getWorkoutDayByIdResponse403
  | getWorkoutDayByIdResponse404
  | getWorkoutDayByIdResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayByIdResponse =
  | getWorkoutDayByIdResponseSuccess
  | getWorkoutDayByIdResponseError;

export const getGetWorkoutDayByIdUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDayById = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayByIdResponse> => {
  return customFetch<getWorkoutDayByIdResponse>(
    getGetWorkoutDayByIdUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get workout plan by id
 */
export type getWorkoutPlanByIdResponse200 = {
  data: GetWorkoutPlanById200;
  status: 200;
};

export type getWorkoutPlanByIdResponse401 = {
  data: GetWorkoutPlanById401;
  status: 401;
};

export type getWorkoutPlanByIdResponse403 = {
  data: GetWorkoutPlanById403;
  status: 403;
};

export type getWorkoutPlanByIdResponse404 = {
  data: GetWorkoutPlanById404;
  status: 404;
};

export type getWorkoutPlanByIdResponse500 = {
  data: GetWorkoutPlanById500;
  status: 500;
};

export type getWorkoutPlanByIdResponseSuccess =
  getWorkoutPlanByIdResponse200 & {
    headers: Headers;
  };
export type getWorkoutPlanByIdResponseError = (
  | getWorkoutPlanByIdResponse401
  | getWorkoutPlanByIdResponse403
  | getWorkoutPlanByIdResponse404
  | getWorkoutPlanByIdResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanByIdResponse =
  | getWorkoutPlanByIdResponseSuccess
  | getWorkoutPlanByIdResponseError;

export const getGetWorkoutPlanByIdUrl = (id: string) => {
  return `/workout-plans/${id}`;
};

export const getWorkoutPlanById = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkoutPlanByIdResponse> => {
  return customFetch<getWorkoutPlanByIdResponse>(getGetWorkoutPlanByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse400 = {
  data: StartWorkoutSession400;
  status: 400;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse403 = {
  data: StartWorkoutSession403;
  status: 403;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse400
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse403
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a workout session
 */
export type completeWorkoutSessionResponse200 = {
  data: CompleteWorkoutSession200;
  status: 200;
};

export type completeWorkoutSessionResponse400 = {
  data: CompleteWorkoutSession400;
  status: 400;
};

export type completeWorkoutSessionResponse401 = {
  data: CompleteWorkoutSession401;
  status: 401;
};

export type completeWorkoutSessionResponse403 = {
  data: CompleteWorkoutSession403;
  status: 403;
};

export type completeWorkoutSessionResponse404 = {
  data: CompleteWorkoutSession404;
  status: 404;
};

export type completeWorkoutSessionResponse409 = {
  data: CompleteWorkoutSession409;
  status: 409;
};

export type completeWorkoutSessionResponse500 = {
  data: CompleteWorkoutSession500;
  status: 500;
};

export type completeWorkoutSessionResponseSuccess =
  completeWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type completeWorkoutSessionResponseError = (
  | completeWorkoutSessionResponse400
  | completeWorkoutSessionResponse401
  | completeWorkoutSessionResponse403
  | completeWorkoutSessionResponse404
  | completeWorkoutSessionResponse409
  | completeWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type completeWorkoutSessionResponse =
  | completeWorkoutSessionResponseSuccess
  | completeWorkoutSessionResponseError;

export const getCompleteWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  params?: CompleteWorkoutSessionParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}?${stringifiedParams}`
    : `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const completeWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  params?: CompleteWorkoutSessionParams,
  options?: RequestInit,
): Promise<completeWorkoutSessionResponse> => {
  return customFetch<completeWorkoutSessionResponse>(
    getCompleteWorkoutSessionUrl(
      workoutPlanId,
      workoutDayId,
      sessionId,
      params,
    ),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user workout stats
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get my user data and friend code
 */
export type getMeResponse200 = {
  data: GetMe200;
  status: 200;
};

export type getMeResponse401 = {
  data: GetMe401;
  status: 401;
};

export type getMeResponse404 = {
  data: GetMe404;
  status: 404;
};

export type getMeResponse500 = {
  data: GetMe500;
  status: 500;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = (
  | getMeResponse401
  | getMeResponse404
  | getMeResponse500
) & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/friendships/me`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get friends list
 */
export type getFriendsResponse200 = {
  data: GetFriends200Item[];
  status: 200;
};

export type getFriendsResponse401 = {
  data: GetFriends401;
  status: 401;
};

export type getFriendsResponse500 = {
  data: GetFriends500;
  status: 500;
};

export type getFriendsResponseSuccess = getFriendsResponse200 & {
  headers: Headers;
};
export type getFriendsResponseError = (
  | getFriendsResponse401
  | getFriendsResponse500
) & {
  headers: Headers;
};

export type getFriendsResponse =
  | getFriendsResponseSuccess
  | getFriendsResponseError;

export const getGetFriendsUrl = () => {
  return `/friendships/`;
};

export const getFriends = async (
  options?: RequestInit,
): Promise<getFriendsResponse> => {
  return customFetch<getFriendsResponse>(getGetFriendsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Send a friend request by code or email
 */
export type addFriendResponse200 = {
  data: AddFriend200;
  status: 200;
};

export type addFriendResponse400 = {
  data: AddFriend400;
  status: 400;
};

export type addFriendResponse401 = {
  data: AddFriend401;
  status: 401;
};

export type addFriendResponse404 = {
  data: AddFriend404;
  status: 404;
};

export type addFriendResponse500 = {
  data: AddFriend500;
  status: 500;
};

export type addFriendResponseSuccess = addFriendResponse200 & {
  headers: Headers;
};
export type addFriendResponseError = (
  | addFriendResponse400
  | addFriendResponse401
  | addFriendResponse404
  | addFriendResponse500
) & {
  headers: Headers;
};

export type addFriendResponse =
  | addFriendResponseSuccess
  | addFriendResponseError;

export const getAddFriendUrl = () => {
  return `/friendships/`;
};

export const addFriend = async (
  addFriendBody: AddFriendBody,
  options?: RequestInit,
): Promise<addFriendResponse> => {
  return customFetch<addFriendResponse>(getAddFriendUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addFriendBody),
  });
};

/**
 * @summary Get pending friend requests
 */
export type getFriendRequestsResponse200 = {
  data: GetFriendRequests200Item[];
  status: 200;
};

export type getFriendRequestsResponse401 = {
  data: GetFriendRequests401;
  status: 401;
};

export type getFriendRequestsResponse500 = {
  data: GetFriendRequests500;
  status: 500;
};

export type getFriendRequestsResponseSuccess = getFriendRequestsResponse200 & {
  headers: Headers;
};
export type getFriendRequestsResponseError = (
  | getFriendRequestsResponse401
  | getFriendRequestsResponse500
) & {
  headers: Headers;
};

export type getFriendRequestsResponse =
  | getFriendRequestsResponseSuccess
  | getFriendRequestsResponseError;

export const getGetFriendRequestsUrl = () => {
  return `/friendships/requests`;
};

export const getFriendRequests = async (
  options?: RequestInit,
): Promise<getFriendRequestsResponse> => {
  return customFetch<getFriendRequestsResponse>(getGetFriendRequestsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Accept a friend request
 */
export type acceptFriendRequestResponse204 = {
  data: AcceptFriendRequest204;
  status: 204;
};

export type acceptFriendRequestResponse401 = {
  data: AcceptFriendRequest401;
  status: 401;
};

export type acceptFriendRequestResponse404 = {
  data: AcceptFriendRequest404;
  status: 404;
};

export type acceptFriendRequestResponse500 = {
  data: AcceptFriendRequest500;
  status: 500;
};

export type acceptFriendRequestResponseSuccess =
  acceptFriendRequestResponse204 & {
    headers: Headers;
  };
export type acceptFriendRequestResponseError = (
  | acceptFriendRequestResponse401
  | acceptFriendRequestResponse404
  | acceptFriendRequestResponse500
) & {
  headers: Headers;
};

export type acceptFriendRequestResponse =
  | acceptFriendRequestResponseSuccess
  | acceptFriendRequestResponseError;

export const getAcceptFriendRequestUrl = (id: string) => {
  return `/friendships/requests/${id}/accept`;
};

export const acceptFriendRequest = async (
  id: string,
  options?: RequestInit,
): Promise<acceptFriendRequestResponse> => {
  return customFetch<acceptFriendRequestResponse>(
    getAcceptFriendRequestUrl(id),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Decline a friend request
 */
export type declineFriendRequestResponse204 = {
  data: DeclineFriendRequest204;
  status: 204;
};

export type declineFriendRequestResponse401 = {
  data: DeclineFriendRequest401;
  status: 401;
};

export type declineFriendRequestResponse404 = {
  data: DeclineFriendRequest404;
  status: 404;
};

export type declineFriendRequestResponse500 = {
  data: DeclineFriendRequest500;
  status: 500;
};

export type declineFriendRequestResponseSuccess =
  declineFriendRequestResponse204 & {
    headers: Headers;
  };
export type declineFriendRequestResponseError = (
  | declineFriendRequestResponse401
  | declineFriendRequestResponse404
  | declineFriendRequestResponse500
) & {
  headers: Headers;
};

export type declineFriendRequestResponse =
  | declineFriendRequestResponseSuccess
  | declineFriendRequestResponseError;

export const getDeclineFriendRequestUrl = (id: string) => {
  return `/friendships/requests/${id}/decline`;
};

export const declineFriendRequest = async (
  id: string,
  options?: RequestInit,
): Promise<declineFriendRequestResponse> => {
  return customFetch<declineFriendRequestResponse>(
    getDeclineFriendRequestUrl(id),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Get activities feed
 */
export type getFeedResponse200 = {
  data: GetFeed200Item[];
  status: 200;
};

export type getFeedResponse401 = {
  data: GetFeed401;
  status: 401;
};

export type getFeedResponse500 = {
  data: GetFeed500;
  status: 500;
};

export type getFeedResponseSuccess = getFeedResponse200 & {
  headers: Headers;
};
export type getFeedResponseError = (getFeedResponse401 | getFeedResponse500) & {
  headers: Headers;
};

export type getFeedResponse = getFeedResponseSuccess | getFeedResponseError;

export const getGetFeedUrl = () => {
  return `/feed/`;
};

export const getFeed = async (
  options?: RequestInit,
): Promise<getFeedResponse> => {
  return customFetch<getFeedResponse>(getGetFeedUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get activities feed for a specific user
 */
export type getUserFeedResponse200 = {
  data: GetUserFeed200Item[];
  status: 200;
};

export type getUserFeedResponse401 = {
  data: GetUserFeed401;
  status: 401;
};

export type getUserFeedResponse403 = {
  data: GetUserFeed403;
  status: 403;
};

export type getUserFeedResponse500 = {
  data: GetUserFeed500;
  status: 500;
};

export type getUserFeedResponseSuccess = getUserFeedResponse200 & {
  headers: Headers;
};
export type getUserFeedResponseError = (
  | getUserFeedResponse401
  | getUserFeedResponse403
  | getUserFeedResponse500
) & {
  headers: Headers;
};

export type getUserFeedResponse =
  | getUserFeedResponseSuccess
  | getUserFeedResponseError;

export const getGetUserFeedUrl = (userId: string) => {
  return `/feed/users/${userId}`;
};

export const getUserFeed = async (
  userId: string,
  options?: RequestInit,
): Promise<getUserFeedResponse> => {
  return customFetch<getUserFeedResponse>(getGetUserFeedUrl(userId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Toggle powerup on an activity
 */
export type togglePowerupResponse204 = {
  data: TogglePowerup204;
  status: 204;
};

export type togglePowerupResponse401 = {
  data: TogglePowerup401;
  status: 401;
};

export type togglePowerupResponse403 = {
  data: TogglePowerup403;
  status: 403;
};

export type togglePowerupResponse404 = {
  data: TogglePowerup404;
  status: 404;
};

export type togglePowerupResponse500 = {
  data: TogglePowerup500;
  status: 500;
};

export type togglePowerupResponseSuccess = togglePowerupResponse204 & {
  headers: Headers;
};
export type togglePowerupResponseError = (
  | togglePowerupResponse401
  | togglePowerupResponse403
  | togglePowerupResponse404
  | togglePowerupResponse500
) & {
  headers: Headers;
};

export type togglePowerupResponse =
  | togglePowerupResponseSuccess
  | togglePowerupResponseError;

export const getTogglePowerupUrl = (id: string) => {
  return `/feed/activities/${id}/powerup`;
};

export const togglePowerup = async (
  id: string,
  options?: RequestInit,
): Promise<togglePowerupResponse> => {
  return customFetch<togglePowerupResponse>(getTogglePowerupUrl(id), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Delete an activity
 */
export type deleteActivityResponse204 = {
  data: DeleteActivity204;
  status: 204;
};

export type deleteActivityResponse401 = {
  data: DeleteActivity401;
  status: 401;
};

export type deleteActivityResponse403 = {
  data: DeleteActivity403;
  status: 403;
};

export type deleteActivityResponse404 = {
  data: DeleteActivity404;
  status: 404;
};

export type deleteActivityResponse500 = {
  data: DeleteActivity500;
  status: 500;
};

export type deleteActivityResponseSuccess = deleteActivityResponse204 & {
  headers: Headers;
};
export type deleteActivityResponseError = (
  | deleteActivityResponse401
  | deleteActivityResponse403
  | deleteActivityResponse404
  | deleteActivityResponse500
) & {
  headers: Headers;
};

export type deleteActivityResponse =
  | deleteActivityResponseSuccess
  | deleteActivityResponseError;

export const getDeleteActivityUrl = (id: string) => {
  return `/feed/activities/${id}`;
};

export const deleteActivity = async (
  id: string,
  options?: RequestInit,
): Promise<deleteActivityResponse> => {
  return customFetch<deleteActivityResponse>(getDeleteActivityUrl(id), {
    ...options,
    method: "DELETE",
  });
};

/**
 * @summary Get users streak ranking
 */
export type getStreakRankingResponse200 = {
  data: GetStreakRanking200;
  status: 200;
};

export type getStreakRankingResponse401 = {
  data: GetStreakRanking401;
  status: 401;
};

export type getStreakRankingResponse500 = {
  data: GetStreakRanking500;
  status: 500;
};

export type getStreakRankingResponseSuccess = getStreakRankingResponse200 & {
  headers: Headers;
};
export type getStreakRankingResponseError = (
  | getStreakRankingResponse401
  | getStreakRankingResponse500
) & {
  headers: Headers;
};

export type getStreakRankingResponse =
  | getStreakRankingResponseSuccess
  | getStreakRankingResponseError;

export const getGetStreakRankingUrl = () => {
  return `/ranking`;
};

export const getStreakRanking = async (
  options?: RequestInit,
): Promise<getStreakRankingResponse> => {
  return customFetch<getStreakRankingResponse>(getGetStreakRankingUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user training data
 */
export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200;
  status: 200;
};

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401;
  status: 401;
};

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500;
  status: 500;
};

export type getUserTrainDataResponseSuccess = getUserTrainDataResponse200 & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (
  | getUserTrainDataResponse401
  | getUserTrainDataResponse500
) & {
  headers: Headers;
};

export type getUserTrainDataResponse =
  | getUserTrainDataResponseSuccess
  | getUserTrainDataResponseError;

export const getGetUserTrainDataUrl = () => {
  return `/me`;
};

export const getUserTrainData = async (
  options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Upsert user training data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200;
  status: 200;
};

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401;
  status: 401;
};

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500;
  status: 500;
};

export type upsertUserTrainDataResponseSuccess =
  upsertUserTrainDataResponse200 & {
    headers: Headers;
  };
export type upsertUserTrainDataResponseError = (
  | upsertUserTrainDataResponse401
  | upsertUserTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse =
  | upsertUserTrainDataResponseSuccess
  | upsertUserTrainDataResponseError;

export const getUpsertUserTrainDataUrl = () => {
  return `/me`;
};

export const upsertUserTrainData = async (
  upsertUserTrainDataBody: UpsertUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertUserTrainDataBody),
  });
};

/**
 * @summary Chat with AI personal trainer
 */
export type aiChatResponse200 = {
  data: void;
  status: 200;
};

export type aiChatResponseSuccess = aiChatResponse200 & {
  headers: Headers;
};
export type aiChatResponse = aiChatResponseSuccess;

export const getAiChatUrl = () => {
  return `/ai/`;
};

export const aiChat = async (
  options?: RequestInit,
): Promise<aiChatResponse> => {
  return customFetch<aiChatResponse>(getAiChatUrl(), {
    ...options,
    method: "POST",
  });
};
